twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        SiteName: 'Les Blue Angels'

        # Infos détaillées des options dipos pour chaque article (pour info-bulle de balise title, ou infos dans la page du formulaire par ex)
        articleOptionInfo:
            inactif:
                "L'article et ses aperçus ne s'afficheront nulle part. Si on tente d'entrer son url, il y aura une erreur 404 de page non trouvée. Ce filtre prend la main sur tous les autres filtres."
            actif:
                "L'affichage de l'article est activé. C'est le minimum obligatoire pour qu'un article soit visible. D'autres filtres pourront prendre la main ensuite."
            listedOff:
                "La carte d'aperçu ne s'affichera pas en homePage."
            listed:
                "Si désactivé, la carte d'aperçu ne s'affichera pas en homePage."
            epingle:
                "Si activé, la carte d'aperçu sera épinglée pour apparaitre en premier dans la barre infos de la page d'accueil (Catégorie Communiqués), à condition que l'affichage soit activé, et qu'il soit aussi activé pour s'afficher en homepage"
            categorie:
                "Catégorie de l'article"
              
        eventOptionInfo:
            annule:
                "Si l'évènement à été annulé, mais qu'on veut quand même le faire apparaitre. Une mention 'Annulé' apparaitra en rouge en travers de la carte d'aperçu"
            eventBlueAngels:
                "Cocher si l'évènement est organisé par les Blue Angels. Décocher si l'évènement n'a rien à voir avec l'association"


